spring.application.name=EVCharge

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/EVChargeDB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Security
spring.security.user.name=${APP_USERNAME}
spring.security.user.password=${APP_PASSWORD}
jwt.secret.key=oCheieSecretaSiLungaDeCelPutin32DeCaracterePentruCriptare123!

logging.level.org.springframework.security=DEBUG